placesRemember/urls.py
from tkinter.font import names
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

""" Add views and URLs """
from user.views import *
from post.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('user.urls', namespace='accounts')),
    path('', include('post.urls', namespace='posts')),
    path('auth/', include('social_django.urls', namespace='social')), #<--
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from .views import *

app_name = 'post'

urlpatterns = [
    # path('login/', LoginView.as_view(), name='login'),
    path('', HomeView.as_view(), name='home'),
    path('create/', CreateView.as_view(), name='create'),
]

user/urls.py
from django.urls import path, include
from .views import *
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.conf import settings
from django.conf.urls.static import static

app_name = 'user'

urlpatterns = [
    # login
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    # change password
    path('password_change/',
        auth_views.PasswordChangeView.as_view(
            success_url=reverse_lazy('accounts:password_change_done')
        ),
        name='password_change'),
    path('password_change/done/',
        auth_views.PasswordChangeDoneView.as_view(),
        name='password_change_done'),

    # reset password
    path('password_reset', 
        auth_views.PasswordResetView.as_view(
            success_url=reverse_lazy('accounts:password_reset_done')
        ),
        name='password_reset'),
    path('password_reset/done', 
        auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done'),
    path('reset/<uidb64>/<token>/', 
        auth_views.PasswordResetConfirmView.as_view(
            success_url=reverse_lazy('accounts:password_reset_complete')
        ),
        name='password_reset_confirm'),
    path('reset/done', 
        auth_views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete'),

    # register
    path('register/', RegisterView.as_view(), name='register'),

    # edit
    path('edit/', UserEditView.as_view(), name='edit'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

post/models.py
from django.db import models
from django.conf import settings
from django.contrib.gis.db import models as gis_model

class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=200,blank=True, null=True)
    comment = models.TextField(blank=True)
    location = gis_model.PointField(srid=4326, geography=True, null=True, blank=True)

    def __str__(self):
        return self.name

user/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings

def upload_avatar(instance,filename):
    filename = filename[-4:]
    path = 'users/'+instance.username +'_{filename}'
    return path.format(filename=filename)


class UserWithAvatar(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to=upload_avatar,blank=True)

    def __str__(self):
        return f'Avatar for user {self.user.username}'

post/forms.py
import imp
from django import forms
from django.contrib.gis import forms
from .models import Post
class PostForm(forms.Form):
    location = forms.PointField(widget=
        forms.OSMWidget(attrs={'map_width': 800, 'map_height': 500}))
    class Meta:
        models = Post
        fields = ('name','comment',)

user/forms.py
from django import forms
from .models import UserWithAvatar, User
from django.core.files.images import get_image_dimensions

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Re-type Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')
    
    def clean_password2(self):
        cleanedData = self.cleaned_data
        if cleanedData['password'] != cleanedData['password2']:
            raise forms.ValidationError('Password don\'t match')
        return cleanedData['password2']

class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

class UserEditAvatarForm(forms.ModelForm):
    class Meta:
        model = UserWithAvatar
        fields = ('avatar',)

post/views.py
from django.shortcuts import render, HttpResponse
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

from post.forms import PostForm
from .models import Post
class HomeView(TemplateView):
    template_name = 'homepage/home.html'

    def get(self, request):
        return render(request, self.template_name, {'section':'home'})

class CreateView(TemplateView):
    template_name = 'createPR/create.html'
    template_successful_name='homepage/home.html'
    @login_required
    def post(self, request):
        post_form = PostForm(request.POST)
        if post_form.is_valid():
            new_post = post_form.save(commit=False)
            new_post.save()
            return render(request, self.template_successful_name)
        else:
            post_form = PostForm()
        return render(request, self.template_name, {'post_form':post_form})

user/views.py
from django.shortcuts import render, HttpResponse
from django.views.generic import TemplateView
from django.contrib.auth import authenticate, login
from .forms import LoginForm, UserRegistrationForm, UserEditForm, UserEditAvatarForm
from .models import UserWithAvatar

# Login
class LoginView(TemplateView):
    template_name = "account/login.html"

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            cleaned_data = form.cleaned_data
            user = authenticate(request, username = cleaned_data['username'],
                                         password = cleaned_data['password'])
            if user is not None:
                if user.is_active:
                    login(request,user)
                    return HttpResponse('Authenticated'' Successfully')
                else:
                    return HttpResponse('Disabled Account')
            else:
                return HttpResponse('Invalid login')
        else:
            form=LoginForm()
        return render(request, self.template_name, {'form':form})


    def get(self, request):
        current_user = request.user
        return render(request, self.template_name, {'current_user': current_user})

# Registration
class RegisterView(TemplateView):
    template_successful_name = 'account/register_done.html'
    template_name = 'account/register.html'
    def post(self, request):
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            UserWithAvatar.objects.create(user=new_user)
            return render(request, self.template_successful_name,{'new_user':new_user})
        else:
            user_form = UserRegistrationForm()
        return render(request, self.template_name, {'user_form':user_form})

# Edit info
class UserEditView(TemplateView):
    template_name = 'account/edit.html'
    def post(self, request):
        user_form = UserEditForm(instance=request.user, data=request.POST)
        avatar_form = UserEditAvatarForm(
            instance=request.user.userwithavatar, 
            data=request.POST, files=request.FILES)
        if user_form.is_valid() and avatar_form.is_valid():
            user_form.save()
            avatar_form.save()
            return render(request, self.template_name, {'user_form':user_form, 'avatar_form':avatar_form})
        else:
            user_form = UserEditForm(instance=request.user)
            avatar_form = UserEditAvatarForm(instance=request.user.userwithavatar)
        return render(request, self.template_name, {'user_form':user_form, 'avatar_form':avatar_form})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    <link rel="shortcut icon" href="{% static "assets/imgs/favicon.ico" %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static "assets/css/reset.css" %}">
    <link rel="stylesheet" href="{% static "assets/css/base.css" %}">
    <link rel="stylesheet" href="{% static "assets/css/grid.css" %}">
    <link rel="stylesheet" href="{% static "assets/css/style.css" %}">
    {% block another_head %} {% endblock %}
</head>
<body>
    <div class="grid">
        <div class="row no-gutters" id="header">
            <div class="col xl-8 xl-o-2 l-8 l-o-2 m-8 m-o-2 sm- sm-o-2 c-8 c-o-2 header__containter">
                <a href="{% url 'posts:home' %}" class="logo">Places Remember</a>
                {% block sign %}
                {% endblock %}
                
            </div>
        </div>
        <div class="row no-gutters" id="main_body">
            <div class="col xl-8 xl-o-2 l-8 l-o-2 m-8 m-o-2 sm-8 sm-o-2 c-8 c-o-2">
                {% block body %}
                {% endblock %}
            </div>
        </div>
        <footer class="row no-gutters" id="footer">
            <div class="col xl-12 l-12 m-12 sm-12 c-12">
                <p class="footer__text">@viktornguyen !This is an interview test</p>
            </div>
        </footer>
    </div>
</body>
</html>

templates/createPR/create.html
{% extends 'base.html' %}

{% load leaflet_tags %}

{% block another_head %} 
    {{ post_form.media }}
{% endblock %}

{% block title %} Create {% endblock %}

{% block sign %} 
    <div class="user_signed">
        <span class="header__username">Hi, {{ request.user.username }}</span>
        <a href="{% url 'accounts:logout' %}?next=/" class="sign_out">Logout</a>
    </div>
{% endblock %}

{% block body %}
    <div class="grid">
        <div class="row">
            <div class="col xl-6 xl-o-3 l-8 l-o-2 m-12 sm-12 c-12">
                <div class="create_wrapper">
                    <form action="{% url 'posts:create' %}" method="post" class="login_form__form user_form__form grid">
                        {{ post_form.as_p }}
                        <input type="hidden" name="next" value="{{ next }}">
                        <label for="submit" class="row">
                            <div class="user_form__submit_button  col xl-10 l-10 m-12 sm-12 c-12 xl-o-1 l-o-1">
                                <input 
                                    type="submit" value="Login"
                                    class="btn btn-primary"
                                    required>
                            </div>
                        {% csrf_token %}
                        </label>
                    </form>
                </div>
            </div>
        </div>
    </div> 
{% endblock %}

templates/homepage/home.html
<!-- Homepage -->
{%extends "base.html" %}

{% block title %} Places Remember {% endblock %}

{% block sign %} 
    {% if request.user.is_authenticated %}
        <div class="user_signed">
            <span class="header__username">Hi, {{ request.user.username }}</span>
            <a href="{% url 'accounts:logout' %}?next=/" class="sign_out">Logout</a>
        </div>
    {% else %}
        <div class="sign">
            <a href="{% url 'accounts:register' %}" class="sign_up">Register</a>
            <span class="separate"></span>
            <a href="{% url 'accounts:login' %}" class="sign_in">Login</a>
        </div>
    {% endif %}
{% endblock %}

{% block body %}
    {% if request.user.is_authenticated %}
    {% else %}
    <h1 class="greeting">
        Greeting to Places Rememeber App.
    </h1>
    {% endif %}
{% endblock %}